#!/bin/bash

#---- COLORS
RED=$'\e[1;31m'
GRN=$'\e[1;32m'
YLW=$'\e[1;33m'
BLU=$'\e[1;34m'
MAG=$'\e[1;35m'
CYN=$'\e[1;36m'
END=$'\e[0m'

#---- GLOBAL VARIABLES
export pkg_ext="frost"
export LC_ALL=C
export LANG=C

#---- FUNCTION
CHECK_PKG() {
  pkg_name="$@"

  if ! echo "$pkg_name" | grep "\b${pkg_ext}\b$"; then
    printf '%s\n' "${RED}The package format must be .${pkg_ext}${END}"
    return 1
  fi

  if echo "$pkg_name" | grep -qE "[[:space:]]+"; then
    printf '%s\n' "${RED}Do not use spaces in the name.${END}"
    printf '%s\n' "${YLW}Exiting...${END}"
    return 1
  fi

  printf '%s\n' "${YLW}Using pkg_name: ${pkg_name}${END}"
  check_name=$(echo "${pkg_name}" | grep -o "-" | wc -l)

  if [ "$check_name" -lt '2' ] || [ "$check_name" -gt '2' ]; then
    printf '%s\n' "${RED}Error: package name is invalid.${END}"
    printf '%s\n' "${YLW}Example: package_name-build_version.${pkg_ext}${END}"
    return 1
  fi
  return 0
}

CREATE_PKG() {
  pkg_name="$1"

  if [ "$VERBOSE" = 1 ]; then
    if tar -cvf../pkg_name .; then
      printf '%b' "${GRN}The package has been created on ../${pkg_name}\n${END}"
    else
      printf "The package was not created\n"
      exit 1
    fi
  else
    if tar -cf ../${pkg_name} .; then
      printf '%b' "${GRN}The package has been created on ../${pkg_name}\n${END}"
      return 0
    else
      printf "The package was not created\n"
      exit 1
    fi
  fi
}

USAGE() {
  echo "Usage mode"
}

while [ -n "$1" ]; do
  case "$1" in
    --created|-c)
      CMD=$1
      shift
    ;;

    --verbose|-v)
      VERBOSE=1
      shift
    ;;

    *.frost)
      PKG=$1
      shift
    ;;

    *)USAGE
    ;;
  esac
done

#---- START
case "$CMD" in
    --create|-c)
    if [ -z "$CMD" ]; then
      printf '%b' "${red}The package name is required.${end}\n"
      exit 1
    fi
    CHECK_PKG "$PKG" || exit 1
    CREATE_PKG "$PKG"
esac
