#!/bin/bash

#---- COLORS
RED=$'\e[1;31m'
GRN=$'\e[1;32m'
YLW=$'\e[1;33m'
BLU=$'\e[1;34m'
MAG=$'\e[1;35m'
CYN=$'\e[1;36m'
END=$'\e[0m'

#---- GLOBAL VARIABLES
export pkg_ext="fpkg"

#---- FUNCTION
CHECK_PKG() {
  pkg_name="$@"

  if ! echo "$pkg_name" | grep "\b${pkg_ext}\b$"; then
    printf '%s\n' "${RED}The package format must be .fpkg${END}"
    return 1
  fi

  if echo "$pkg_name" | grep -qE "[[:space:]]+"; then
    printf '%s\n' "${RED}Do not use spaces in the name.${END}"
    printf '%s\n' "${YLW}Exiting...${END}"
    return 1
  fi
}

CREATE_PKG() {
  pkg_name="$1"
  
  if tar -cvf ../${pkg_name} .; then
    printf '%b' "${GRN}The package has been created on ../${pkg_name}\n${END}"
    return 0
  else
    printf "The package was not created\n"
    exit 1
  fi
}

#---- START
case "$1" in
  create|-c)
    shift
    if [ -z "$1" ]; then
      printf '%b' "${red}The package name is required.${end}\n"
      exit 1
    fi
    CHECK_PKG "$@" || exit 1
    CREATE_PKG "$@"
esac
